plugins { id "net.neoforged.moddev" }
ext.rails = [
        compat : ["cart-behavior", "chunk-flags", "item-setid", "recipe-1212", "nbt-optional", "store-codec", "savedtype-string", "ids-factory", "sprite-atlasfn", "tooltip-display"],
        loader : ["cartext-rail", "model-blockstate"],
        renames: [(/BuiltInRegistries\.(\w+)\.get\(/): 'BuiltInRegistries.$1.getValue('],
]
apply from: "${rootDir}/gradle/neoforge-band.gradle"
