plugins { id "net.neoforged.moddev" }
ext.rails = [
        compat : ["cart-behavior", "chunk-flags", "item-setid", "recipe-1212", "nbt-optional", "store-codec", "savedtype-string", "ids-factory", "sprite-atlasmanager", "tooltip-display", "shot-scale", "perms-set", "lines-gizmo", "net-payload"],
        loader : ["cartext-rail", "model-blockstate", "overlay-none"],
        renames: ["getvalue", "ride3", "mc1211"],
]
apply from: "${rootDir}/gradle/neoforge-band.gradle"
