plugins { id "fabric-loom" }
ext.rails = [
        compat : ["cart-behavior", "chunk-flags", "item-setid", "recipe-1212", "nbt-optional", "store-codec", "savedtype-string", "ids-factory", "sprite-atlasfn", "tooltip-display", "shot-plain", "perms-level"],
        loader : ["model-blockstate", "overlay-events"],
        renames: ["getvalue"],
]
apply from: "${rootDir}/gradle/fabric-band.gradle"
