plugins { id "fabric-loom" }
ext.rails = [
        compat : ["cart-behavior", "chunk-moving", "item-setid", "recipe-1212", "nbt-plain", "store-factory", "ids-factory", "sprite-atlasfn", "tooltip-context", "shot-plain", "perms-level", "lines-buffer", "net-payload"],
        loader : ["model-delegate", "overlay-events", "net-payload"],
        renames: ["getvalue"],
]
apply from: "${rootDir}/gradle/fabric-band.gradle"
