plugins { id "fabric-loom" }
ext.rails = [
        compat : ["cart-behavior", "chunk-flags", "item-setid", "recipe-1212", "nbt-optional", "store-codec", "savedtype-string", "ids-factory", "sprite-atlasmanager", "tooltip-display", "shot-scale", "perms-set"],
        loader : ["model-blockstate", "overlay-worldevents"],
        renames: ["getvalue", "ride3", "mc1211"],
]
apply from: "${rootDir}/gradle/fabric-band.gradle"
